// Pure validators shared by the browser and Cloud Functions.
// Source of truth: src/js/utils/. functions/src/lib/shared/ is generated by `npm run sync:shared`.

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/;
const NAME_RE = /^[\p{L}\p{M}][\p{L}\p{M}' .-]*$/u;

export function normaliseEmail(raw) {
  return typeof raw === 'string' ? raw.trim().toLowerCase() : '';
}

/** @returns {string|null} an error message, or null when valid. */
export function validateEmail(raw) {
  const email = normaliseEmail(raw);
  if (!email) return 'Enter an email address.';
  if (email.length > 254 || !EMAIL_RE.test(email)) return 'Enter a valid email address, like name@example.com.';
  return null;
}

/** Collapse whitespace so "  Mary   Anne " becomes "Mary Anne". */
export function cleanText(raw) {
  return typeof raw === 'string' ? raw.replace(/\s+/g, ' ').trim() : '';
}

export function validateName(raw, { label = 'Name', required = true } = {}) {
  const value = cleanText(raw);
  if (!value) return required ? `Enter the ${label.toLowerCase()}.` : null;
  if (value.length < 2) return `${label} is too short.`;
  if (value.length > 60) return `${label} must be 60 characters or fewer.`;
  if (!NAME_RE.test(value)) return `${label} can only use letters, spaces, hyphens and apostrophes.`;
  return null;
}

/**
 * Normalises a phone number to E.164. Kenyan formats (07xx, 01xx, 254xx, +254xx) are
 * recognised; any other country must be entered with a leading + or 00.
 * @returns {string|null}
 */
export function normalisePhone(raw) {
  if (typeof raw !== 'string') return null;
  let digits = raw.replace(/[\s().-]/g, '');
  if (digits.startsWith('00')) digits = `+${digits.slice(2)}`;
  if (!/^\+?\d+$/.test(digits)) return null;
  let e164;
  if (digits.startsWith('+')) e164 = digits;
  else if (digits.startsWith('0') && digits.length === 10) e164 = `+254${digits.slice(1)}`;
  else if (digits.startsWith('254') && digits.length === 12) e164 = `+${digits}`;
  else return null;
  return /^\+[1-9]\d{7,14}$/.test(e164) ? e164 : null;
}

export function validatePhone(raw, { label = 'Phone number' } = {}) {
  if (!cleanText(raw)) return `Enter the ${label.toLowerCase()}.`;
  return normalisePhone(raw) ? null : `Enter a valid ${label.toLowerCase()}, like 0712 345 678 or +44 20 7946 0958.`;
}

/** Accepts ISO dates (YYYY-MM-DD) for a real calendar day, aged between minAge and maxAge. */
export function validateDateOfBirth(raw, { now = new Date(), minAge = 4, maxAge = 100 } = {}) {
  const value = typeof raw === 'string' ? raw.trim() : '';
  if (!value) return 'Enter the date of birth.';
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(value);
  if (!m) return 'Enter the date of birth as day, month and year.';
  const [y, mo, d] = [Number(m[1]), Number(m[2]), Number(m[3])];
  const dt = new Date(Date.UTC(y, mo - 1, d));
  if (dt.getUTCFullYear() !== y || dt.getUTCMonth() !== mo - 1 || dt.getUTCDate() !== d) return 'That date does not exist.';
  if (dt > now) return 'The date of birth cannot be in the future.';
  let age = now.getUTCFullYear() - y;
  if (now.getUTCMonth() < mo - 1 || (now.getUTCMonth() === mo - 1 && now.getUTCDate() < d)) age -= 1;
  if (age < minAge) return `Applicants must be at least ${minAge} years old.`;
  if (age > maxAge) return 'Check the year of birth.';
  return null;
}

const COMMON_PASSWORDS = new Set([
  'password', 'password1', 'password123', '12345678', '123456789', '1234567890', 'qwertyuiop',
  'iloveyou1', 'welcome123', 'admin1234', 'letmein123', 'kenya2024', 'kenya12345',
]);

/** @returns {string[]} everything wrong with the password (empty when acceptable). */
export function validatePassword(password, { email = '' } = {}) {
  const issues = [];
  const pw = typeof password === 'string' ? password : '';
  if (pw.length < 8) issues.push('Use at least 8 characters.');
  if (pw.length > 128) issues.push('Use 128 characters or fewer.');
  if (!/\p{L}/u.test(pw)) issues.push('Include at least one letter.');
  if (!/\d/.test(pw)) issues.push('Include at least one number.');
  if (COMMON_PASSWORDS.has(pw.toLowerCase())) issues.push('That password is too common.');
  const local = normaliseEmail(email).split('@')[0];
  if (local && local.length >= 4 && pw.toLowerCase().includes(local)) issues.push('Do not include your email name.');
  return issues;
}
