// Copies the validators shared by the browser and Cloud Functions into functions/src/lib/shared/.
// Edit the files in src/js/utils/, then run `npm run sync:shared`. `--check` fails if they have drifted.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const FILES = ['validation.js', 'application-schema.js', 'application-status.js', 'roles.js'];
const checkOnly = process.argv.includes('--check');
let stale = 0;

for (const name of FILES) {
  const source = readFileSync(resolve(root, 'src/js/utils', name), 'utf8');
  const output = `// GENERATED by scripts/sync-shared.mjs from src/js/utils/${name}. Do not edit here.\n${source}`;
  const dest = resolve(root, 'functions/src/lib/shared', name);
  let current = '';
  try { current = readFileSync(dest, 'utf8'); } catch { /* not generated yet */ }
  if (current === output) continue;
  if (checkOnly) {
    console.error(`stale: functions/src/lib/shared/${name} (run npm run sync:shared)`);
    stale += 1;
  } else {
    mkdirSync(dirname(dest), { recursive: true });
    writeFileSync(dest, output);
    console.log(`synced ${name}`);
  }
}
if (checkOnly && stale) process.exit(1);
