// GENERATED by scripts/sync-shared.mjs from src/js/utils/application-status.js. Do not edit here.
// Admissions workflow states, shared by the admin UI and the decideApplication function.

export const APPLICATION_STATUSES = Object.freeze([
  'submitted', 'under_review', 'info_requested', 'waitlisted', 'approved', 'rejected',
]);

/** Applications that still need a decision (used for duplicate checks and the admin queue). */
export const OPEN_STATUSES = Object.freeze(['submitted', 'under_review', 'info_requested', 'waitlisted']);

export const STATUS_LABELS = Object.freeze({
  submitted: 'Submitted',
  under_review: 'Under review',
  info_requested: 'Information requested',
  waitlisted: 'Waitlisted',
  approved: 'Approved',
  rejected: 'Not accepted',
});

/** Admin action -> resulting status. */
export const DECISIONS = Object.freeze({
  start_review: 'under_review',
  request_info: 'info_requested',
  waitlist: 'waitlisted',
  approve: 'approved',
  reject: 'rejected',
});

export const DECISION_LABELS = Object.freeze({
  start_review: 'Start review',
  request_info: 'Request information',
  waitlist: 'Waitlist',
  approve: 'Approve',
  reject: 'Decline',
});

const TRANSITIONS = Object.freeze({
  submitted: ['under_review', 'info_requested', 'waitlisted', 'approved', 'rejected'],
  under_review: ['info_requested', 'waitlisted', 'approved', 'rejected'],
  info_requested: ['under_review', 'waitlisted', 'approved', 'rejected'],
  waitlisted: ['under_review', 'approved', 'rejected'],
  approved: [],
  rejected: [],
});

export function canTransition(from, to) {
  return (TRANSITIONS[from] ?? []).includes(to);
}

/** The admin actions that make sense for an application in the given status. */
export function availableDecisions(status) {
  return Object.entries(DECISIONS)
    .filter(([, target]) => canTransition(status, target))
    .map(([decision]) => decision);
}
