// GENERATED by scripts/sync-shared.mjs from src/js/utils/application-schema.js. Do not edit here.
// Admissions application schema, shared by the registration form and the submitApplication function.
import {
  cleanText, normaliseEmail, normalisePhone, validateDateOfBirth, validateEmail, validateName, validatePhone,
} from './validation.js';

export const GENDERS = Object.freeze(['male', 'female', 'other']);
export const NATIONALITIES = Object.freeze(['kenyan', 'other']);
export const RELATIONSHIPS = Object.freeze(['parent', 'guardian', 'sibling', 'other']);
export const CONSENT_VERSION = '2026-10';

/** Which fields belong to which step of the form (the last step is review and consent). */
export const STEP_FIELDS = Object.freeze([
  ['firstName', 'middleName', 'surname', 'dateOfBirth'],
  ['gender', 'email', 'phoneNumber', 'nationality'],
  ['guardianName', 'relationship', 'guardianPhone', 'emergencyContact'],
  ['consent'],
]);

const PROGRAMME_ID_RE = /^[a-z0-9][a-z0-9-]{0,59}$/;

function oneOf(value, allowed, message) {
  return allowed.includes(value) ? null : message;
}

/**
 * Validates and normalises an application.
 * @returns {{ ok: boolean, value: object, errors: Record<string, string> }}
 */
export function validateApplication(input, { now = new Date() } = {}) {
  const src = input && typeof input === 'object' ? input : {};
  const str = (key) => (typeof src[key] === 'string' ? src[key].trim() : '');
  const errors = {};
  const value = {};
  const check = (key, error, normalised) => {
    if (error) errors[key] = error;
    else value[key] = normalised;
  };

  check('firstName', validateName(str('firstName'), { label: 'First name' }), cleanText(str('firstName')));
  check('middleName', validateName(str('middleName'), { label: 'Middle name', required: false }), cleanText(str('middleName')));
  check('surname', validateName(str('surname'), { label: 'Surname' }), cleanText(str('surname')));
  check('dateOfBirth', validateDateOfBirth(str('dateOfBirth'), { now }), str('dateOfBirth'));
  check('gender', oneOf(str('gender'), GENDERS, 'Select a gender.'), str('gender'));
  check('email', validateEmail(str('email')), normaliseEmail(str('email')));
  check('phoneNumber', validatePhone(str('phoneNumber')), normalisePhone(str('phoneNumber')));
  check('nationality', oneOf(str('nationality'), NATIONALITIES, 'Select a nationality.'), str('nationality'));
  check('guardianName', validateName(str('guardianName'), { label: 'Guardian name' }), cleanText(str('guardianName')));
  check('relationship', oneOf(str('relationship'), RELATIONSHIPS, 'Select the relationship.'), str('relationship'));
  check('guardianPhone', validatePhone(str('guardianPhone'), { label: "Guardian's phone number" }), normalisePhone(str('guardianPhone')));
  check('emergencyContact', validateName(str('emergencyContact'), { label: 'Emergency contact name' }), cleanText(str('emergencyContact')));

  const programmeId = str('programmeId');
  if (programmeId && !PROGRAMME_ID_RE.test(programmeId)) errors.programmeId = 'That programme is not recognised.';
  else value.programmeId = programmeId || null;

  if (src.consent !== true) errors.consent = 'Confirm that the details are correct and that CFL may process them.';
  else value.consent = true;

  return { ok: Object.keys(errors).length === 0, value, errors };
}
