import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '../..');

describe('shared modules', () => {
  it.each(['validation.js', 'application-schema.js', 'application-status.js', 'roles.js'])(
    'functions/src/lib/shared/%s is an exact copy of src/js/utils (run npm run sync:shared)',
    (name) => {
      const source = readFileSync(resolve(root, 'src/js/utils', name), 'utf8');
      const copy = readFileSync(resolve(root, 'functions/src/lib/shared', name), 'utf8');
      expect(copy).toBe(`// GENERATED by scripts/sync-shared.mjs from src/js/utils/${name}. Do not edit here.\n${source}`);
    },
  );
});
